version: '3.7'

services:
    rabbitmq:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5673:5672"


    db:
        hostname: mongo
        image: mongo:latest
        ports:
            - "27018:27017"